{% set version = "2022.8.1" %}
{% set sha256 = "d8f24394c84ce6c66e0e63f10d1ac5216e5e70e5191b71c1d9a28b0a0c87246e" %}

package:
  name: restraintlib
  version: {{ version }}

source:
  url: https://github.com/mkowiel/restraintlib/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - cctbx-base >=2020.8
    - scikit-learn >=1.0, <1.1
    - pandas
    - six

test:
  imports:
    - restraintlib
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests/*.py
    - tests/*.cif
    - tests/*.pdb
  commands:
    - pytest

about:
  home: https://github.com/mkowiel/restraintlib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bond length and angle restraints for DNA and RNA oligonucleotides

extra:
  recipe-maintainers:
    - mkowiel
    - dabrze
